# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('castles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('history', models.TextField()),
                ('words', models.CharField(blank=True, max_length=150, null=True)),
                ('coat_of_arms', models.TextField()),
                ('house_image', models.ImageField(upload_to='houses/')),
                ('books', models.ManyToManyField(to='books.Book')),
                ('castle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='castles.Castle')),
            ],
        ),
    ]
