# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
    ]
