# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Castle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('region', models.CharField(choices=[('NT', 'NORTH'), ('WE', 'Westerlands'), ('ES', 'Eastlands'), ('ST', 'SOUTH')], max_length=10)),
            ],
        ),
    ]
