# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('autor', models.CharField(blank=True, default='George R.R. Martin', max_length=40)),
                ('date_published', models.DateField()),
                ('num_pages', models.IntegerField(max_length=12)),
                ('isbn', models.CharField(max_length=80)),
            ],
        ),
    ]
