# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('continent', models.CharField(choices=[('WT', 'Westeros'), ('ES', 'Essos'), ('OH', 'Other')], max_length=10)),
                ('religion', models.CharField(max_length=50)),
            ],
        ),
    ]
